<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>sleeper</groupId>
        <artifactId>aws</artifactId>
        <version>0.29.0-SNAPSHOT</version>
    </parent>

    <artifactId>diffblue-report-agregation</artifactId>

    <dependencies>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>core</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>ingest-batcher-core</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>ingest-batcher-job-creator</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>ingest-batcher-store</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>ingest-batcher-submitter</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>ingest-core</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>ingest-runner</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>ingest-starter</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>ingest-tracker</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>parquet</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>clients</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>statestore</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>statestore-committer-core</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>statestore-lambda</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>configuration</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>compaction-core</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>compaction-job-creation</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>compaction-job-creation-lambda</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>compaction-job-execution</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>compaction-task-creation</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>compaction-tracker</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>query-core</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>query-lambda</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>query-runner</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>system-test-cdk</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>system-test-configuration</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>system-test-data-generation</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>system-test-drivers</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>system-test-dsl</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>sleeper</groupId>-->
<!--            <artifactId>system-test-suite</artifactId>-->
<!--            <version>0.29.0-SNAPSHOT</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>garbage-collector</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>splitter-core</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>splitter-lambda</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>cdk</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>sketches</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>athena</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>common-invoke-tables</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>common-job</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>common-task</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>dynamodb-tools</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>localstack-test</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>bulk-import-core</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>bulk-import-eks</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>bulk-import-runner</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>bulk-import-starter</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>bulk-export-core</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>bulk-export-runner</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>bulk-export-starter</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>cdk-custom-resources</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>cdk-environment</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>metrics</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>distribution</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>trino</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>build</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>build-uptime-lambda</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>sleeper</groupId>
            <artifactId>example-iterators</artifactId>
            <version>0.29.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
    <plugins>
        <plugin>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-maven</artifactId>
            <executions>
                <execution>
                    <id>run-mutation-tests</id>
                    <phase>none</phase>
                </execution>
                <execution>
                    <id>put-it-together</id>
                    <goals>
                        <goal>report-aggregate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
    </build>

</project>